name: DevSecOps Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r app/requirements.txt

      - name: Run Pytest
        run: python -m pytest app/tests/

  sast:
    name: SAST (Bandit + CodeQL)
    runs-on: ubuntu-latest
    needs: test
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Bandit SAST Scan
        run: |
          pip install bandit
          bandit -r app/ -f json -o bandit-report.json || true
          bandit -r app/ --severity-level high

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-security-report
          path: bandit-report.json

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: CodeQL Anlayis
        uses: github/codeql-action/analyze@v3
        
  sca-secret:
    name: SCA (Snyk) + Secerets Scan
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r app/requirements.txt

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Dependency Scan (Snyk)
        working-directory: app
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=requirements.txt --package-manager=pip --severity-threshold=high

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  container-scan:
    name: Container Scan (Trivy)
    runs-on: ubuntu-latest
    needs: sca-secret
    env:
      IMAGE_NAME: devsecops-app
    steps:
      - uses: actions/checkout@v4

      - name: Build Image for Scan
        run: docker build -t ${{ env.IMAGE_NAME }}:scan .
        
      - name: Trivy Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:scan'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
        

      - name: Trivy Full Report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:scan'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-vulnerabilty-scan
          path: trivy-results.sarif

  build-deploy:
    name: Build and Push
    needs: container-scan
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: devsecops-app
      REGISTRY_NAME: ${{ secrets.ACR_LOGIN_SERVER }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t $REGISTRY_NAME/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push $REGISTRY_NAME/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag $REGISTRY_NAME/${{ env.IMAGE_NAME }}:${{ github.sha }} $REGISTRY_NAME/${{ env.IMAGE_NAME }}:latest
          docker push $REGISTRY_NAME/${{ env.IMAGE_NAME }}:latest